name: Deploy Private GitHub repository to Client server cpanel
on:
  push:
    branches:
      - deploy
      - main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.softvencefsd.xyz
          username: alexdelic91@alexdelic91.softvencefsd.xyz
          password: "softvencefsd_alexdelic91"

  Deploy-Trekarius:
      name: Deploy to Trekarius Server
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/deploy'
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
          with:
            fetch-depth: 2

        - name: FTP-Deploy-Action
          uses: SamKirkland/FTP-Deploy-Action@4.3.0
          with:
            server: 82.29.184.44
            username: adam
            password: "123456@#adam"